[package]
name = "passgen"
version = "0.1.0"
edition = "2021"
authors = ["RoaringCow"]
license = "MIT"
description = "Password generator"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
